GRAPHS: [CN]

BENCHMARK:
  REPORT: True
  REPEAT_TIMES: 3

OUTPUT_PER_QUERY:
  REPORT: True
  INCLUDE_INTERACTIVE_TABLE: True
  INCLUDE_NETWORK_GRAPH: True

MGDB:
  DATA_SOURCE:
    FOLDER_PATH: data/external/mgdb
    CYPHER: 
      DATABASE_GROUP: MGDB_NEO4J
      LOAD_DATA: False
    SPARQL: 
      DATABASE_GROUP: MGDB_BLAZEGRAPH
      LOAD_DATA: False

  # Available languages and tools: [PYTHON, SQL, CYPHER, SPARQL, CLINGO, BASHLOG]
  LANGUAGES_AND_TOOLS: [PYTHON, SQL, CYPHER, SPARQL] #, CLINGO, BASHLOG]

  QUERIES:
    RUN: [UNARY_SEARCH_ANCESTORS, BINARY_SEARCH_ANCESTORS, UNARY_SEARCH_DESCENDANTS, BINARY_SEARCH_DESCENDANTS, LOWEST_COMMON_ANCESTORS]

    # Available queries
    UNARY_SEARCH_ANCESTORS:
      PIDS: [63244]
    
    BINARY_SEARCH_ANCESTORS:
      PIDS: [63244]
    
    UNARY_SEARCH_DESCENDANTS:
      PIDS: [63188]

    BINARY_SEARCH_DESCENDANTS:
      PIDS: [63188]
    
    LOWEST_COMMON_ANCESTORS:
      PID1: 63244
      PID2: 119280

FISH:
  DATA_SOURCE:
    MAX_HAMMING_NUMBER: [10**3, 10**4, 10**5, 10**6, 10**7, 10**8] # 10**9 too large to be stored in data type: Id out of range
    CYPHER: 
      DATABASE_GROUP: MGDB_NEO4J
      LOAD_DATA: False
    SPARQL: 
      DATABASE_GROUP: MGDB_BLAZEGRAPH
      LOAD_DATA: False

  # Available languages and tools: [CLINGO, BASHLOG]
  LANGUAGES_AND_TOOLS: [CLINGO]

  QUERIES:
    RUN: [LOWEST_COMMON_ANCESTORS]

    # Available queries
    UNARY_SEARCH_ANCESTORS:
      PIDS: []
    
    BINARY_SEARCH_ANCESTORS:
      PIDS: []
    
    UNARY_SEARCH_DESCENDANTS:
      PIDS: []

    BINARY_SEARCH_DESCENDANTS:
      PIDS: []
    
    LOWEST_COMMON_ANCESTORS:
      PID1: 216
      PID2: 240

SAIL:
  DATA_SOURCE:
    MAX_HAMMING_NUMBER: [10**3, 10**4, 10**5, 10**6, 10**7, 10**8]
    CYPHER: 
      DATABASE_GROUP: MGDB_NEO4J
      LOAD_DATA: False
    SPARQL: 
      DATABASE_GROUP: MGDB_BLAZEGRAPH
      LOAD_DATA: False

  # Available languages and tools: [CLINGO, BASHLOG]
  LANGUAGES_AND_TOOLS: [CLINGO]

  QUERIES:
    RUN: [LOWEST_COMMON_ANCESTORS]

    # Available queries
    UNARY_SEARCH_ANCESTORS:
      PIDS: []
    
    BINARY_SEARCH_ANCESTORS:
      PIDS: []
    
    UNARY_SEARCH_DESCENDANTS:
      PIDS: []

    BINARY_SEARCH_DESCENDANTS:
      PIDS: []
    
    LOWEST_COMMON_ANCESTORS:
      PID1: 216
      PID2: 240

# Citation Network
CN:
  DATA_SOURCE:
    FOLDER_PATH: data/external/cn
    CYPHER: 
      DATABASE_GROUP: CN_NEO4J
      LOAD_DATA: False # Set it to True if you run this code for the first time

  QUERIES:
    RUN: [BASIC_MEASURES, RESEARCH_QUESTION_EXTRACTION, INFLUENTIAL_PAPER_DETECTION_BY_DEGREECENTRALITY]
    
    # Available queries
    BASIC_MEASURES:
      METRICS: [numofnodes, numofedges, avgdegree, diameter, clusteringcoefficient, avgpathlength]
      LANGUAGES_AND_TOOLS: [PYTHON]
    
    RESEARCH_QUESTION_EXTRACTION:
      KEYWORDS: ["sentiment analysis"] # Lower case
      LANGUAGES_AND_TOOLS: [CYPHER]

    INFLUENTIAL_PAPER_DETECTION_BY_DEGREECENTRALITY:
      K: 3 # Return top k influential papers
      LANGUAGES_AND_TOOLS: [PYTHON]
    
  INFLUENTIAL_PAPERS:
    REPORT: True
    K: 3 # This value must be less or equal to [QUERIES][DETECTION_QUERY][K]
    DETECTION_QUERY: INFLUENTIAL_PAPER_DETECTION_BY_DEGREECENTRALITY

  # Available languages and tools
  LANGUAGES_AND_TOOLS: [PYTHON, CYPHER]