GRAPHS: [MGDB]

BENCHMARK:
  REPEAT_TIMES: 3
  REPORT: True

MGDB:
  DATA_SOURCE:
    FOLDER_PATH: data/external/mgdb
    CYPHER: 
      DATABASE_GROUP: MGDB_NEO4J
      LOAD_DATA: False
    SPARQL: 
      DATABASE_GROUP: MGDB_BLAZEGRAPH
      LOAD_DATA: False

  # Available languages and tools: [PYTHON, SQL, CYPHER, SPARQL, CLINGO, BASHLOG]
  LANGUAGES_AND_TOOLS: [PYTHON, SQL, CYPHER, SPARQL, CLINGO, BASHLOG]

  QUERIES:
    RUN: [UNARY_SEARCH_ANCESTORS, UNARY_SEARCH_DESCENDANTS]

    # Available queries
    UNARY_SEARCH_ANCESTORS:
      PIDS: [63244]
    
    UNARY_SEARCH_DESCENDANTS:
      PIDS: [63244]

