GRAPHS: [MGDB]

BENCHMARK:
  REPORT: False
  REPEAT_TIMES: 1

OUTPUT_PER_QUERY:
  REPORT: False
  INCLUDE_INTERACTIVE_TABLE: True
  INCLUDE_NETWORK_GRAPH: True

MGDB:
  DATA_SOURCE:
    FOLDER_PATH: data/external/mgdb
    CYPHER: 
      DATABASE_GROUP: MGDB_NEO4J
      LOAD_DATA: False
    SPARQL: 
      DATABASE_GROUP: MGDB_BLAZEGRAPH
      LOAD_DATA: False

  # Available languages and tools: [PYTHON, SQL, CYPHER, SPARQL, CLINGO, BASHLOG, LOGICA]
  LANGUAGES_AND_TOOLS: [PYTHON]

  QUERIES:
    RUN: [UNARY_SEARCH_ANCESTORS] 
   
    # Available queries
    UNARY_SEARCH_ANCESTORS:
      PIDS: [63244]
    
    BINARY_SEARCH_ANCESTORS:
      PIDS: [63244]
    
    UNARY_SEARCH_DESCENDANTS:
      PIDS: [63188]

    BINARY_SEARCH_DESCENDANTS:
      PIDS: [63188]
    
    LOWEST_COMMON_ANCESTORS:
      PID1: 63244
      PID2: 119280

    LOWEST_COMMON_ANCESTORS_PATH:
      PID1: 63244
      PID2: 119280