#!/bin/bash
###############################################################
# This script was generated by bashlog
# For more information, visit thomasrebele.org/projects/bashlog
###############################################################

export LC_ALL=C
mkdir -p tmp
rm -f tmp/*
if type mawk > /dev/null; then awk="mawk"; else awk="awk"; fi
sort="sort "
check() { grep -- $1 <(sort --help) > /dev/null; }
check "--buffer-size" && sort="$sort --buffer-size=50% "
check "--parallel"    && sort="$sort --parallel=2 "

read_ntriples() { $awk -F" " '{ sub(" ", "\t"); sub(" ", "\t"); sub(/ \.$/, ""); print $0 }' "$@"; }
conv_ntriples() { $awk -F$'\t' '{ print $1 " " $2 " " $3 " ." }'; }


$sort -t $'\t' -k 1 -k 2 -u \
<(join -t $'\t' -1 1 -2 1 -o 1.2,2.2 \
    <($sort -t $'\t' -k 1 \
        <($awk -v FS=$'\t' ' 
              BEGIN { 
               out0c2_cond1["<advised_by>"] = "1"; 
              }
            
             (($2) in out0c2_cond1){ print $1 FS $3 } 
              ' ./data/raw/mgdb/bashlog/advised.tsv)) \
    <($sort -t $'\t' -k 1 \
        <($awk -v FS=$'\t' ' 
              BEGIN { 
               out0c2_cond1["<author>"] = "1"; 
              }
            
             (($2) in out0c2_cond1){ print $1 FS $3 } 
              ' ./data/raw/mgdb/bashlog/dissertation.tsv)))

 rm -f tmp/*
