#!/bin/bash
###############################################################
# This script was generated by bashlog
# For more information, visit thomasrebele.org/projects/bashlog
###############################################################

export LC_ALL=C
mkdir -p tmp
rm -f tmp/*
if type mawk > /dev/null; then awk="mawk"; else awk="awk"; fi
sort="sort "
check() { grep -- $1 <(sort --help) > /dev/null; }
check "--buffer-size" && sort="$sort --buffer-size=20% "
check "--parallel"    && sort="$sort --parallel=2 "

read_ntriples() { $awk -F" " '{ sub(" ", "\t"); sub(" ", "\t"); sub(/ \.$/, ""); print $0 }' "$@"; }
conv_ntriples() { $awk -F$'\t' '{ print $1 " " $2 " " $3 " ." }'; }




mkfifo tmp/lock_mat1; ( $sort -t $'\t' -k 2 ./data/query/mgdb/bashlog/interim_advise.tsv > tmp/mat1; mv tmp/lock_mat1 tmp/done_mat1; cat tmp/done_mat1 > /dev/null & exec 3> tmp/done_mat1; exec 3>&-; ) & 

# plan
touch tmp/mat2 tmp/mat3
$awk -v FS=$'\t' ' ($2 == "63244") { print $1 FS "63244" >> "tmp/mat2" } 
 ($2 == "119280") { print $1 FS "119280" >> "tmp/mat3" } 
  ' ./data/query/mgdb/bashlog/interim_advise.tsv 

$sort -t $'\t' -k 1 -k 2 -k 3 -u \
<($awk -v FS=$'\t' '  { print "63244" FS "119280" FS $1} 
      ' \
    <(join -t $'\t' -1 1 -2 1 -o 1.1,2.1 \
        <($sort -t $'\t' -k 1 -u \
            <($awk -v FS=$'\t' '  { print $1} 
                  ' \
                <($sort -t $'\t' -k 1 -k 2 -u tmp/mat2 \
                         | tee tmp/full4 > tmp/delta4
                    while 
                    
                    $sort -t $'\t' -k 1 -k 2 -u \
                        <($awk -v FS=$'\t' '  { print $1 FS "63244"} 
                              ' \
                            <(cat tmp/lock_mat1 1>&2 2>/dev/null ;  \
                                join -t $'\t' -1 2 -2 1 -o 1.1,1.2,2.1 tmp/mat1 \
                                <($sort -t $'\t' -k 1 -u \
                                    <($awk -v FS=$'\t' '  { print $1} 
                                          ' tmp/delta4)))) \
                         | comm -23 - tmp/full4 > tmp/new4;
                    
                    mv tmp/new4 tmp/delta4 ; 
                    $sort -u --merge -o tmp/full4 tmp/full4 tmp/delta4 ; 
                    [ -s tmp/delta4 ]; 
                    do continue; done
                    
                    rm tmp/delta4
                    cat tmp/full4))) \
        <($sort -t $'\t' -k 1 -u \
            <($awk -v FS=$'\t' '  { print $1} 
                  ' \
                <($sort -t $'\t' -k 1 -k 2 -u tmp/mat3 \
                         | tee tmp/full5 > tmp/delta5
                    while 
                    
                    $sort -t $'\t' -k 1 -k 2 -u \
                        <($awk -v FS=$'\t' '  { print $1 FS "119280"} 
                              ' \
                            <(cat tmp/lock_mat1 1>&2 2>/dev/null ;  \
                                join -t $'\t' -1 2 -2 1 -o 1.1,1.2,2.1 tmp/mat1 \
                                <($sort -t $'\t' -k 1 -u \
                                    <($awk -v FS=$'\t' '  { print $1} 
                                          ' tmp/delta5)))) \
                         | comm -23 - tmp/full5 > tmp/new5;
                    
                    mv tmp/new5 tmp/delta5 ; 
                    $sort -u --merge -o tmp/full5 tmp/full5 tmp/delta5 ; 
                    [ -s tmp/delta5 ]; 
                    do continue; done
                    
                    rm tmp/delta5
                    cat tmp/full5)))))

 rm -f tmp/*
