#!/bin/bash
###############################################################
# This script was generated by bashlog
# For more information, visit thomasrebele.org/projects/bashlog
###############################################################

export LC_ALL=C
mkdir -p data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752
rm -f data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/*
if type mawk > /dev/null; then awk="mawk"; else awk="awk"; fi
sort="sort "
check() { grep -- $1 <(sort --help) > /dev/null; }
check "--buffer-size" && sort="$sort --buffer-size=20% "
check "--parallel"    && sort="$sort --parallel=2 "

read_ntriples() { $awk -F" " '{ sub(" ", "\t"); sub(" ", "\t"); sub(/ \.$/, ""); print $0 }' "$@"; }
conv_ntriples() { $awk -F$'\t' '{ print $1 " " $2 " " $3 " ." }'; }



mkfifo data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/lock_mat0; ( $sort -t $'\t' -k 1 \
    <($awk -v FS=$'\t' ' 
          BEGIN { 
           out0c2_cond1["<author>"] = "1"; 
          }
        
         (($2) in out0c2_cond1){ print $1 FS $3 } 
          ' ./data/raw/mgdb/bashlog/dissertation.tsv) > data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/mat0; mv data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/lock_mat0 data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/done_mat0; cat data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/done_mat0 > /dev/null & exec 3> data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/done_mat0; exec 3>&-; ) & 

# plan
touch data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/mat1 data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/mat2
$awk -v FS=$'\t' ' ($2 == "<advised_by>") { print $1 FS $3 >> "data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/mat1" } 
 ($3 == "63188" && $2 == "<advised_by>") { print $1 >> "data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/mat2" } 
  ' ./data/raw/mgdb/bashlog/advised.tsv 


mkfifo data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/lock_mat3; ( $sort -t $'\t' -k 1 \
    <(cat data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/lock_mat0 1>&2 2>/dev/null ;  \
        join -t $'\t' -1 1 -2 1 -o 1.2,2.2 \
        <($sort -t $'\t' -k 1 data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/mat1) data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/mat0) > data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/mat3; mv data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/lock_mat3 data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/done_mat3; cat data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/done_mat3 > /dev/null & exec 3> data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/done_mat3; exec 3>&-; ) & 

# plan
$sort -t $'\t' -k 1 -k 2 -u \
<(join -t $'\t' -1 1 -2 1 -o 1.1,2.2 \
    <($sort -t $'\t' -k 1 -u \
        <($awk -v FS=$'\t' '  { print $2} 
              ' \
            <($sort -t $'\t' -k 1 -k 2 -u \
                    <($awk -v FS=$'\t' '  { print "63188" FS $3} 
                          ' \
                        <(cat data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/lock_mat0 1>&2 2>/dev/null ;  \
                            join -t $'\t' -1 1 -2 1 -o 1.1,2.1,2.2 \
                            <($sort -t $'\t' -k 1 -u data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/mat2) data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/mat0)) \
                     | tee data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/full4 > data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/delta4
                while 
                
                $sort -t $'\t' -k 1 -k 2 -u \
                    <($awk -v FS=$'\t' '  { print "63188" FS $3} 
                          ' \
                        <(cat data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/lock_mat3 1>&2 2>/dev/null ;  \
                            join -t $'\t' -1 1 -2 1 -o 1.1,2.1,2.2 \
                            <($sort -t $'\t' -k 1 -u \
                                <($awk -v FS=$'\t' '  { print $2} 
                                      ' data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/delta4)) data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/mat3)) \
                     | comm -23 - data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/full4 > data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/new4;
                
                mv data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/new4 data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/delta4 ; 
                $sort -u --merge -o data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/full4 data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/full4 data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/delta4 ; 
                [ -s data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/delta4 ]; 
                do continue; done
                
                rm data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/delta4
                cat data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752/full4))) \
    <($sort -t $'\t' -k 1 \
        <($awk -v FS=$'\t' ' 
              BEGIN { 
               out0c2_cond1["<name>"] = "1"; 
              }
            
             (($2) in out0c2_cond1){ print $1 FS $3 } 
              ' ./data/raw/mgdb/bashlog/person.tsv)))

rm -rf data/query/mgdb/bashlog/unary_search_descendants_for_63188_tmp8676442752
