$schema: "http://json-schema.org/draft-07/schema#"
description: GELATO configuration schema
required:
  - GRAPHS
  - BENCHMARK
  - OUTPUT_PER_QUERY
  - MGDB
  - FISH
  - SAIL
  - CN

properties:

  GRAPHS:
    type: array
    uniqueItems: True
    items:
      type: string
      enum: [MGDB, FISH, SAIL, CN]
  
  BENCHMARK:
    type: object
    required: [REPORT, REPEAT_TIMES]
    properties:
      REPORT:
        type: boolean
      REPEAT_TIMES:
        type: integer
        minimum: 1
  
  OUTPUT_PER_QUERY:
    type: object
    required: [REPORT, INCLUDE_INTERACTIVE_TABLE, INCLUDE_NETWORK_GRAPH]
    properties:
      REPORT:
        type: boolean
      INCLUDE_INTERACTIVE_TABLE:
        type: boolean
      INCLUDE_NETWORK_GRAPH:
        type: boolean

  MGDB:
    type: object
    required: [DATA_SOURCE, LANGUAGES_AND_TOOLS, QUERIES]
    properties:
      DATA_SOURCE:
        type: object
        required: [FOLDER_PATH, CYPHER, SPARQL]
        properties:
          FOLDER_PATH:
            type: string
            pattern: "data/external/*"
          CYPHER:
            type: object
            required: [DATABASE_GROUP, LOAD_DATA]
            properties:
              DATABASE_GROUP:
                type: string
              LOAD_DATA:
                type: boolean
          SPARQL:
            type: object
            required: [DATABASE_GROUP, LOAD_DATA]
            properties:
              DATABASE_GROUP:
                type: string
              LOAD_DATA:
                type: boolean
      LANGUAGES_AND_TOOLS:
        type: array
        uniqueItems: True
        items:
          type: string
          enum: [PYTHON, SQL, CYPHER, SPARQL, CLINGO, BASHLOG]
      QUERIES:
        type: object
        required: [RUN, UNARY_SEARCH_ANCESTORS, BINARY_SEARCH_ANCESTORS, UNARY_SEARCH_DESCENDANTS]
        properties:
          RUN:
            type: array
            uniqueItems: True
            items:
              type: string
              enum: [UNARY_SEARCH_ANCESTORS, BINARY_SEARCH_ANCESTORS, UNARY_SEARCH_DESCENDANTS, BINARY_SEARCH_DESCENDANTS, LOWEST_COMMON_ANCESTORS]
          UNARY_SEARCH_ANCESTORS:
            type: object
            required: [PIDS]
            properties:
              PIDS:
                type: array
                uniqueItems: True
          BINARY_SEARCH_ANCESTORS:
            type: object
            required: [PIDS]
            properties:
              PIDS:
                type: array
                uniqueItems: True
          UNARY_SEARCH_DESCENDANTS:
            type: object
            required: [PIDS]
            properties:
              PIDS:
                type: array
                uniqueItems: True
          BINARY_SEARCH_DESCENDANTS:
            type: object
            required: [PIDS]
            properties:
              PIDS:
                type: array
                uniqueItems: True
          LOWEST_COMMON_ANCESTORS:
            type: object
            required: [PID1, PID2]
            properties:
              PID1: 
                type: integer
              PID2:
                type: integer

FISH:
    type: object
    required: [DATA_SOURCE, LANGUAGES_AND_TOOLS, QUERIES]
    properties:
      DATA_SOURCE:
        type: object
        required: [MAX_HAMMING_NUMBER, CYPHER, SPARQL]
        properties:
          MAX_HAMMING_NUMBER:
            type: integer
            minimum: 1
          CYPHER:
            type: object
            required: [DATABASE_GROUP, LOAD_DATA]
            properties:
              DATABASE_GROUP:
                type: string
              LOAD_DATA:
                type: boolean
          SPARQL:
            type: object
            required: [DATABASE_GROUP, LOAD_DATA]
            properties:
              DATABASE_GROUP:
                type: string
              LOAD_DATA:
                type: boolean
      LANGUAGES_AND_TOOLS:
        type: array
        uniqueItems: True
        items:
          type: string
          enum: [PYTHON, SQL, CYPHER, SPARQL, CLINGO, BASHLOG]
      QUERIES:
        type: object
        required: [RUN, UNARY_SEARCH_ANCESTORS, BINARY_SEARCH_ANCESTORS, UNARY_SEARCH_DESCENDANTS]
        properties:
          RUN:
            type: array
            uniqueItems: True
            items:
              type: string
              enum: [UNARY_SEARCH_ANCESTORS, BINARY_SEARCH_ANCESTORS, UNARY_SEARCH_DESCENDANTS, BINARY_SEARCH_DESCENDANTS, LOWEST_COMMON_ANCESTORS]
          UNARY_SEARCH_ANCESTORS:
            type: object
            required: [PIDS]
            properties:
              PIDS:
                type: array
                uniqueItems: True
          BINARY_SEARCH_ANCESTORS:
            type: object
            required: [PIDS]
            properties:
              PIDS:
                type: array
                uniqueItems: True
          UNARY_SEARCH_DESCENDANTS:
            type: object
            required: [PIDS]
            properties:
              PIDS:
                type: array
                uniqueItems: True
          BINARY_SEARCH_DESCENDANTS:
            type: object
            required: [PIDS]
            properties:
              PIDS:
                type: array
                uniqueItems: True
          LOWEST_COMMON_ANCESTORS:
            type: object
            required: [PID1, PID2]
            properties:
              PID1: 
                type: integer
              PID2:
                type: integer

SAIL:
    type: object
    required: [DATA_SOURCE, LANGUAGES_AND_TOOLS, QUERIES]
    properties:
      DATA_SOURCE:
        type: object
        required: [MAX_HAMMING_NUMBER, CYPHER, SPARQL]
        properties:
          MAX_HAMMING_NUMBER:
            type: integer
            minimum: 1
          CYPHER:
            type: object
            required: [DATABASE_GROUP, LOAD_DATA]
            properties:
              DATABASE_GROUP:
                type: string
              LOAD_DATA:
                type: boolean
          SPARQL:
            type: object
            required: [DATABASE_GROUP, LOAD_DATA]
            properties:
              DATABASE_GROUP:
                type: string
              LOAD_DATA:
                type: boolean
      LANGUAGES_AND_TOOLS:
        type: array
        uniqueItems: True
        items:
          type: string
          enum: [PYTHON, SQL, CYPHER, SPARQL, CLINGO, BASHLOG]
      QUERIES:
        type: object
        required: [RUN, UNARY_SEARCH_ANCESTORS, BINARY_SEARCH_ANCESTORS, UNARY_SEARCH_DESCENDANTS]
        properties:
          RUN:
            type: array
            uniqueItems: True
            items:
              type: string
              enum: [UNARY_SEARCH_ANCESTORS, BINARY_SEARCH_ANCESTORS, UNARY_SEARCH_DESCENDANTS, BINARY_SEARCH_DESCENDANTS, LOWEST_COMMON_ANCESTORS]
          UNARY_SEARCH_ANCESTORS:
            type: object
            required: [PIDS]
            properties:
              PIDS:
                type: array
                uniqueItems: True
          BINARY_SEARCH_ANCESTORS:
            type: object
            required: [PIDS]
            properties:
              PIDS:
                type: array
                uniqueItems: True
          UNARY_SEARCH_DESCENDANTS:
            type: object
            required: [PIDS]
            properties:
              PIDS:
                type: array
                uniqueItems: True
          BINARY_SEARCH_DESCENDANTS:
            type: object
            required: [PIDS]
            properties:
              PIDS:
                type: array
                uniqueItems: True
          LOWEST_COMMON_ANCESTORS:
            type: object
            required: [PID1, PID2]
            properties:
              PID1: 
                type: integer
              PID2:
                type: integer
